/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"
#include "gpio.h"
#include "timer.h"
#include "coreM4.h"


uint8_t nmbr=0;
uint8_t numbers_of_7segment[10]={
			0x3f,
			0x06,
			0x5b,
			0x4f,
			0x66,
			0x6d,
			0x7d,
			0x07,
			0x7f,
			0x6f
	};

void update_of_7segment(uint8_t number){
	gpio_writeto_output_pin(GPIOD, GPIO_PIN_NO_0, ((number>>0)&0x01));
	gpio_writeto_output_pin(GPIOD, GPIO_PIN_NO_1, ((number>>1)&0x01));
	gpio_writeto_output_pin(GPIOD, GPIO_PIN_NO_2, ((number>>2)&0x01));
	gpio_writeto_output_pin(GPIOD, GPIO_PIN_NO_3, ((number>>3)&0x01));
	gpio_writeto_output_pin(GPIOD, GPIO_PIN_NO_4, ((number>>4)&0x01));
	gpio_writeto_output_pin(GPIOD, GPIO_PIN_NO_5, ((number>>5)&0x01));
	gpio_writeto_output_pin(GPIOD, GPIO_PIN_NO_6, ((number>>6)&0x01));
}


void SysTick_Handler(){

	gpio_toggleto_output_pin(GPIOD, GPIO_PIN_NO_15);

	update_of_7segment(numbers_of_7segment[nmbr]);
	if(nmbr<9){
		nmbr++;
	}else{
		nmbr=0;
	}
}


int main(void)
{

	GPIO_Handle_t blue ={GPIOD,{GPIO_PIN_NO_15,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};
	gpio_init(&blue);

	GPIO_Handle_t gpioA_7segmentA ={GPIOD,{GPIO_PIN_NO_0,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};
	GPIO_Handle_t gpioA_7segmentB ={GPIOD,{GPIO_PIN_NO_1,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};
	GPIO_Handle_t gpioA_7segmentC ={GPIOD,{GPIO_PIN_NO_2,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};
	GPIO_Handle_t gpioA_7segmentD ={GPIOD,{GPIO_PIN_NO_3,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};
	GPIO_Handle_t gpioA_7segmentE ={GPIOD,{GPIO_PIN_NO_4,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};
	GPIO_Handle_t gpioA_7segmentF ={GPIOD,{GPIO_PIN_NO_5,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};
	GPIO_Handle_t gpioA_7segmentG ={GPIOD,{GPIO_PIN_NO_6,GPIO_MODE_OUT,GPIO_SPEED_MEDIUM,GPIO_OTYPE_PP,GPIO_NO_PUPD}};

	gpio_init(&gpioA_7segmentA);
	gpio_init(&gpioA_7segmentB);
	gpio_init(&gpioA_7segmentC);
	gpio_init(&gpioA_7segmentD);
	gpio_init(&gpioA_7segmentE);
	gpio_init(&gpioA_7segmentF);
	gpio_init(&gpioA_7segmentG);

	systick_config(SYSTEM_FREQ/1);

	while(1){

	}
}
